/* eslint-disable jsx-a11y/no-noninteractive-tabindex -- A named, horizontally scrollable table region needs keyboard focus. */
import type { Metadata } from "next";
import { ProsePage } from "@/components/ProsePage";
import { SiteLink as Link } from "@/components/SiteLink";
import { restaurantById } from "@/lib/directory";
import { buildPageMetadata } from "@/lib/site";

export const metadata: Metadata = buildPageMetadata({ title: "How to choose ramen: real Canadian menu comparisons", description: "Compare actual ramen prices, vegan choices, pork versus chicken stock, tsukemen and paid upgrades using six Canadian restaurant menus checked in September 2026.", path: "/guides/choosing-ramen" });
function Listing({ id, children }: { id: string; children: React.ReactNode }) {
  const restaurant = restaurantById.get(id);
  return restaurant ? <Link href={restaurant.canonicalPath}>{children}</Link> : <>{children}</>;
}

export default function ChoosingRamen() {
  return <ProsePage eyebrow="Ramen Scout menu research" title="Choose the bowl, not just the restaurant." intro="Six official Canadian menus show why broth names, vegetarian labels and headline prices need a second look. These are source-based comparisons and our calculations—not taste reviews or claims of personal visits." updated="September 19, 2026">
    <nav className="guide-toc" aria-label="Guide sections"><a href="#stock">Stock versus topping</a><a href="#vegan">Vegan choices</a><a href="#format">Soup or dipping noodles</a><a href="#budget">Budget examples</a><a href="#branch">Branch differences</a><a href="#method">Research method</a></nav>
    <h2 id="stock">1. A chicken topping does not establish chicken-only stock</h2>
    <p>At <Listing id="ramen_ca_f43841040f91ed0862cc">Ramen Gojiro in Vancouver</Listing>, Basic Ramen uses a pork-and-chicken soup and offers karaage or chashu toppings. Its chicken-chashu Shoyu also uses both stocks. Selecting chicken changes the topping, not the broth underneath. Gojiro’s rich/light option is another separate choice: a light setting does not remove the pork ingredient. <a href="https://ramengojiro.com/menu.html">Gojiro’s menu</a> supports those distinctions, but publishes no prices on that page, so there is no evidence-backed budget ranking for its bowls here.</p>
    <p><Listing id="ramen_ca_d803b44fefafa757981e">Tokiwa in Edmonton</Listing> provides the reverse example: its six-hour chicken soup section normally comes with pork chashu. The menu offers a $2 chicken substitution. Tokyo Tonkotsu and Chuka Soba are both $16, so comparing them isolates a stock choice at the same base price. If avoiding pork is essential, ask about the entire recipe and preparation—not only the named stock or visible meat. <a href="https://tokiwaramen.ca/menu">Tokiwa’s menu</a> is the source for the ingredients and surcharge; it is not a halal certificate.</p>
    <h2 id="vegan">2. Vegan menus and vegetarian substitutions are different evidence</h2>
    <p>DANBO’s Vancouver menu makes this comparison unusually straightforward: its four permanent vegan flavours mirror four pork-broth flavours at the same regular prices. Classic is $12.95 on either menu, while Miso is $14.45. Choosing the vegan base does not impose a price premium in those examples. The regular menu’s broth-richness setting refers to lard; the vegan version uses white sesame oil. Follow the correct ordering path instead of mixing settings from the two menus. The <a href="https://ramendanbo.com/our-menu-vancouver/">official Vancouver menu</a> also separates vegan sides and lunch combinations.</p>
    <p>At <Listing id="ramen_ca_376b924d920c31ee2b03">Isshin’s Vaughan branch in Concord</Listing>, the vegetarian section explicitly offers egg-free noodle substitution. Kale noodles are marked vegan and cost $2 to substitute, but that does not independently establish every default vegetarian bowl as vegan. Similarly, Crafty Ramen’s tofu-and-veggie-stock choices are useful leads, not proof about every sauce. Our <Link href="/features/vegan">complete vegan bowl filter</Link> is deliberately narrower than “vegetarian” or “tofu.” For allergies, none of these labels establishes separate equipment or freedom from cross-contact.</p>
    <h2 id="format">3. Decide whether you want soup, dipping noodles or a low-broth bowl</h2>
    <p>Isshin Vaughan’s $22.30 Stone Bowl Shoyu Kotteri Tsukemen combines seafood and pork in a separate dipping soup. Its $18.50 Classic Shoyu is a soup bowl, so the $3.80 difference buys a different format rather than simply a higher grade of the same bowl. The dipping noodles are served cold unless hot noodles are requested; the restaurant gives a six-minute noodle-boiling time, not a six-minute door-to-table promise. Curry Cheese Tsukemen is $22.95 and includes cheese, egg and chicken cutlets. The curry name should not be read as a vegetarian label. These distinctions come from the <a href="https://www.ramenisshin.ca/vaughanmenu">Vaughan-specific menu</a>, not another Isshin branch.</p>
    <p><Listing id="ramen_ca_fff7ee5d989f8ea60fae">Crafty Ramen in Guelph</Listing> lists chilled Redeye and Kimchi Mazemen at $14.75, compared with $16.85 for Tokyo Salaryman soup ramen. That is a $2.10 format difference. Redeye includes pork and egg; Kimchi offers a protein choice. At <Listing id="ramen_ca_1d358958d30659cd7b34">Shiki Menya in Calgary</Listing>, O.G. Mazemen is described as low-broth rather than a conventional full soup bowl. Read each restaurant’s wording instead of assuming all mazemen is served identically. Sources: <a href="https://craftyramen.com/pages/crafty-ramen-restaurant">Crafty’s restaurant menu</a> and <a href="https://shikimenya.ca/pages/shiki-menya-summer-menu">Shiki’s linked SS2026 menu</a>.</p>
    <h2 id="budget">4. Compare the order you would actually buy</h2>
    <p>These worked examples use recorded menu prices in Canadian dollars. Totals exclude applicable tax, tip, delivery charges and any other purchases. They are calculations, not live checkout quotes.</p>
    <div className="table-wrap" tabIndex={0} role="region" aria-label="Worked menu budgets"><table className="comparison-table"><caption>Source menus checked September 19, 2026</caption><thead><tr><th scope="col">Example order</th><th scope="col">Calculation</th><th scope="col">Why it matters</th></tr></thead><tbody>
      <tr><th scope="row">DANBO Classic + ramen egg</th><td>$12.95 + $2 = $14.95</td><td>The egg costs extra and makes this unsuitable as a vegan combination.</td></tr>
      <tr><th scope="row">Crafty Tokyo Salaryman + advertised combo</th><td>$16.85 + $2.50 = $19.35</td><td>The combo is a half snack and a pop, not a full side.</td></tr>
      <tr><th scope="row">Shiki O.G. Mazemen + grilled-cheese variation</th><td>$21 + $2 = $23</td><td>The upgrade removes most of the base-price gap to its $24 Authentic Miso.</td></tr>
      <tr><th scope="row">Shiki Chili Goma + Goma DX upgrade</th><td>$22 + $6 = $28</td><td>The pictured base price does not include the added chashu and egg. This bowl flags peanuts.</td></tr>
    </tbody></table></div>
    <p>Children’s bowls, snacks, meal kits and frozen retail packs are not comparable with a full adult restaurant bowl. Nor is a restaurant’s cheapest observed item necessarily its cheapest available dish. We show named examples so you can inspect exactly what went into a comparison.</p>
    <h2 id="branch">5. A shared brand menu can still have branch exceptions</h2>
    <p>DANBO is a useful example of why an exact address matters. The Vancouver menu marks the $4.95 plant-based bun as Main Street only, fried rice as Kerrisdale only, and mochi ice cream as Lonsdale only. A vegan Classic plus the bun is $17.90 before extras—but that is a Main Street plan, not a promise at Robson. Start with the branch’s <a href="https://ramendanbo.com/locations/">official location entry</a>, then its menu exceptions. Our listings keep those addresses separate even when the underlying broth selection is shared.</p>
    <p>Timing and payment also change a viable plan. Tokiwa’s menu specifies cash or debit, no split bills, and an automatic 18% gratuity for tables of six or more. Those restrictions can matter more to a group than a small difference in bowl price. A published closing time elsewhere does not establish the last seating, kitchen cutoff or current queue. Use <Link href="/search">nearby search</Link> to compare alternatives, then confirm time-sensitive requirements directly.</p>
    <h2 id="method">How this guide was researched</h2>
    <p>Ramen Scout compared first-party menu pages on September 19, 2026, and read Shiki Menya’s linked menu image. We selected these examples because they demonstrate concrete ordering trade-offs, not because they are the “best” restaurants. Menu descriptions inform the ingredient comparisons; the arithmetic is ours. No diner review, star rating or promotional claim was converted into a taste judgment.</p>
    <p>Prices can change after the check. Brand-wide menus are identified as such, and a branch exception is not generalized to the chain. Halal certification and allergy safety require evidence beyond a dish name. See <Link href="/methodology">our verification definitions</Link> or <Link href="/corrections">report an outdated detail</Link>. Published by <Link href="/about">Ramen Scout / Nocturnal Devs</Link>.</p>
  </ProsePage>;
}
